version: '3'
services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/vanni/elasticsearch:7.6.2-ik-pinyin
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./es/stop.dic:/usr/share/elasticsearch/config/analysis-ik/custom_stopword.dic
      - ./es/synonym.dic:/usr/share/elasticsearch/config/analysis-ik/custom_synonym.dic
    ports: ["9200:9200", "9300:9300"]
    restart: always
volumes:
  elastic-data:
    driver: local