version: '3'
services:
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    volumes:
      - ./es/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: ["5601:5601"]
    restart: always