version: '3'
services:
  kibana:
    image: rabbitmq
    container_name: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports: ["5671:5671","15672:15672"]
    restart: always